version: '3.9'

services:
  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: src/ApiGateways/OcelotApiGateway/Dockerfile

  webhealthstatus:
    image: ${DOCKER_REGISTRY-}webhealthstatus
    build:
      context: .
      dockerfile: src/WebApps/WebHealthStatus/Dockerfile


  basket.api:
    image: ${DOCKER_REGISTRY-}basket-api
    build:
      context: .
      dockerfile: src/Services/Basket.API/Dockerfile


  customer.api:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: src/Services/Customer.API/Dockerfile


  inventory.product.api:
    image: ${DOCKER_REGISTRY-}inventoryproductapi
    build:
      context: .
      dockerfile: src/Services/Inventory.Product.API/Dockerfile


  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/Services/Ordering.API/Dockerfile


  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: src/Services/Product.API/Dockerfile


  hangfire.api:
    image: ${DOCKER_REGISTRY-}hangfireapi
    build:
      context: .
      dockerfile: src/Services/Hangfire.API/Dockerfile

#database section
  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
  
  productdb: 
    image: mysql:8.0.32
    
  customerdb: 
    image: postgres:alpine3.17
    
  basketdb:
    image: redis
  
  inventorydb:
    image: mongo
    
#infrastructure section
  rabbitmq:
    image: rabbitmq:3-management-alpine
    
  pgadmin:
    image: dpage/pgadmin4
    
  portainer: 
    image: portainer/portainer-ce
    
  elasticsearch:
    image: elasticsearch:7.17.9
  
  kibana:
    image: kibana:7.17.9

networks:
  default:
    name: microservices
    driver: bridge
    
volumes:
  sqlserver_data:
    name: sqlserver_data
  mysql_data:
    name: mysql_data
  postgres_data:
    name: postgres_data
  elasticsearch_data:
    name: elasticsearch_data
  jaeger_data:
    name: jaeger_data
  mongo_data:
    name: mongo_data
  pgadmin_data:
    name: pgadmin_data
  
